[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Credentials removed - set in Netlify dashboard
# Rotate anon key in Supabase and update in Netlify env vars

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
